version: '3.8'
services:
  api:
    build: ./src/SmartBudget.Api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=smartbudget;Username=smartuser;Password=smartpass
      - Jwt__Key=ThisIsADevSecretKeyChangeMe
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass
      POSTGRES_DB: smartbudget
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
